namespace Epfo.Grievance.Application;

public sealed record AccessScope(long UserId, int OfficeId, IReadOnlyCollection<string> Roles) { public bool IsSuperAdmin => Roles.Contains("SUPERADMIN", StringComparer.OrdinalIgnoreCase); public bool IsAdmin => Roles.Contains("ADMIN", StringComparer.OrdinalIgnoreCase); }
public sealed record LoginRequest(string Username, string Password, string Role);
public sealed record LoginResponse(string AccessToken, DateTime ExpiresAt, string Username, string DisplayName, string OfficeCode, string OfficeName, IReadOnlyCollection<string> Roles);
public sealed record SwitchOfficeRequest(string OfficeCode);
public sealed record SignUpRequest(string Username, string Password, string DisplayName, string? Email, string OfficeCode);
public sealed record CreateUserRequest(string Username, string Password, string DisplayName, string? Email, string RoleCode, string OfficeCode);
public sealed record UpdateUserRoleRequest(string RoleCode);
public sealed record UpdateUserStatusRequest(bool IsEnabled);
public sealed record UserResponse(long UserId, string Username, string DisplayName, string? Email, string OfficeCode, IReadOnlyCollection<string> Roles, bool IsEnabled);
public sealed record UserReferenceData(IReadOnlyCollection<RoleOption> Roles, IReadOnlyCollection<OfficeOption> Offices);
public sealed record RoleOption(string RoleCode, string DisplayName);
public sealed record OfficeOption(string OfficeCode, string OfficeName);
public sealed record CreateCaseRequest(Dictionary<string, string> Fields);
public sealed record CaseListItem(string ReferenceNumber, string Status, DateTime ReceivedAt, IReadOnlyDictionary<string, string?> Fields);
public sealed record CaseDetails(string ReferenceNumber, string ModuleId, string Status, DateTime ReceivedAt, IReadOnlyDictionary<string, string?> Fields);
public sealed record ChangeCaseStatusRequest(string Status, string? Remarks);
public sealed record CaseStatusHistoryItem(string Status, string? Remarks, DateTime ChangedAt);
public sealed record DashboardSummary(int TotalCases, int OpenCases, int ActiveModules);
public sealed record JdCaseListItem(string ReferenceNumber, string Status, string? Uan, string? MemberId, DateTime ReceivedAt, DateTime? DaAcknowledgedAt, string? DaDecision, DateTime? SsAcknowledgedAt, string? SsDecision, string? RejectionReason);
public sealed record JdDecisionRequest(string Decision, string? RejectionReason);
public sealed record JdStatusHistoryItem(string Status, string? Remarks, DateTime ChangedAt);
public interface IAuthService { Task<LoginResponse?> LoginAsync(LoginRequest request, CancellationToken cancellationToken); Task<LoginResponse?> SwitchOfficeAsync(SwitchOfficeRequest request, AccessScope scope, CancellationToken cancellationToken); Task<UserResponse> SignUpAsync(SignUpRequest request, CancellationToken cancellationToken); Task<IReadOnlyCollection<OfficeOption>> GetOfficesAsync(CancellationToken cancellationToken); }
public interface IUserService { Task<UserResponse> CreateAsync(CreateUserRequest request, AccessScope scope, CancellationToken cancellationToken); Task<IReadOnlyCollection<UserResponse>> ListAsync(AccessScope scope, CancellationToken cancellationToken); Task<UserResponse?> UpdateRoleAsync(long userId, UpdateUserRoleRequest request, AccessScope scope, CancellationToken cancellationToken); Task<UserResponse?> UpdateStatusAsync(long userId, UpdateUserStatusRequest request, AccessScope scope, CancellationToken cancellationToken); Task<UserReferenceData> GetReferenceDataAsync(AccessScope scope, CancellationToken cancellationToken); }
public interface ICaseService { Task<IReadOnlyCollection<CaseListItem>> ListAsync(string moduleId, string? search, AccessScope scope, CancellationToken cancellationToken); Task<IReadOnlyCollection<CaseListItem>> ReportAsync(string moduleId, string? search, AccessScope scope, CancellationToken cancellationToken); Task<CaseDetails?> GetAsync(string referenceNumber, AccessScope scope, CancellationToken cancellationToken); Task<IReadOnlyCollection<CaseStatusHistoryItem>?> HistoryAsync(string referenceNumber, AccessScope scope, CancellationToken cancellationToken); Task<CaseDetails> CreateAsync(string moduleId, CreateCaseRequest request, AccessScope scope, CancellationToken cancellationToken); Task<CaseDetails?> ChangeStatusAsync(string referenceNumber, ChangeCaseStatusRequest request, AccessScope scope, CancellationToken cancellationToken); Task<DashboardSummary> GetDashboardSummaryAsync(AccessScope scope, CancellationToken cancellationToken); }
public interface IJointDeclarationService { Task<JdCaseListItem> CreateIntakeAsync(CreateCaseRequest request, AccessScope scope, CancellationToken cancellationToken); Task<IReadOnlyCollection<JdCaseListItem>> ListAsync(string stage, AccessScope scope, CancellationToken cancellationToken); Task<JdCaseListItem?> AcknowledgeDaAsync(string referenceNumber, AccessScope scope, CancellationToken cancellationToken); Task<JdCaseListItem?> DecideDaAsync(string referenceNumber, JdDecisionRequest request, AccessScope scope, CancellationToken cancellationToken); Task<JdCaseListItem?> AcknowledgeSsAsync(string referenceNumber, AccessScope scope, CancellationToken cancellationToken); Task<JdCaseListItem?> DecideSsAsync(string referenceNumber, JdDecisionRequest request, AccessScope scope, CancellationToken cancellationToken); Task<IReadOnlyCollection<JdStatusHistoryItem>> HistoryAsync(string referenceNumber, AccessScope scope, CancellationToken cancellationToken); Task<IReadOnlyCollection<JdCaseListItem>> ReportAsync(DateTime? from, DateTime? to, AccessScope scope, CancellationToken cancellationToken); }
