namespace Epfo.Grievance.Domain;

public sealed class Office { public int OfficeId { get; set; } public string OfficeCode { get; set; } = null!; public string OfficeName { get; set; } = null!; public string City { get; set; } = null!; public bool IsActive { get; set; } = true; }
public sealed class Role { public short RoleId { get; set; } public string RoleCode { get; set; } = null!; public string DisplayName { get; set; } = null!; public bool IsActive { get; set; } = true; }
public sealed class User { public long UserId { get; set; } public int OfficeId { get; set; } public string Username { get; set; } = null!; public string? Email { get; set; } public string DisplayName { get; set; } = null!; public string PasswordHash { get; set; } = null!; public bool IsEnabled { get; set; } public Office Office { get; set; } = null!; public ICollection<UserRole> UserRoles { get; set; } = []; }
public sealed class UserRole { public long UserId { get; set; } public short RoleId { get; set; } public User User { get; set; } = null!; public Role Role { get; set; } = null!; }
public sealed class CaseType { public short CaseTypeId { get; set; } public string TypeCode { get; set; } = null!; public string DisplayName { get; set; } = null!; public bool IsActive { get; set; } = true; }
public sealed class CaseStatus { public short CaseStatusId { get; set; } public string StatusCode { get; set; } = null!; public string DisplayName { get; set; } = null!; public bool IsClosed { get; set; } }
public sealed class ServiceArea { public int ServiceAreaId { get; set; } public string AreaCode { get; set; } = null!; public string DisplayName { get; set; } = null!; public bool IsActive { get; set; } = true; }
public sealed class GrievanceCase { public long CaseId { get; set; } public string ReferenceNumber { get; set; } = null!; public int OfficeId { get; set; } public short CaseTypeId { get; set; } public int? ServiceAreaId { get; set; } public short CaseStatusId { get; set; } public string? Uan { get; set; } public string? MemberId { get; set; } public string? EstablishmentCode { get; set; } public string? PpoNumber { get; set; } public string? MemberName { get; set; } public string? MobileNumber { get; set; } public string? Email { get; set; } public string? Subject { get; set; } public string? Remarks { get; set; } public DateTime ReceivedAt { get; set; } public DateTime? DueAt { get; set; } public DateTime? ClosedAt { get; set; } public long? CreatedByUserId { get; set; } public DateTime CreatedAt { get; set; } public CaseType CaseType { get; set; } = null!; public CaseStatus CaseStatus { get; set; } = null!; public ICollection<CaseAttribute> Attributes { get; set; } = []; public JointDeclarationDetail? JointDeclarationDetail { get; set; } }
public sealed class CaseAttribute { public long CaseAttributeId { get; set; } public long CaseId { get; set; } public string AttributeName { get; set; } = null!; public string? AttributeValue { get; set; } public GrievanceCase Case { get; set; } = null!; }
public sealed class CaseStatusHistory { public long CaseStatusHistoryId { get; set; } public long CaseId { get; set; } public short CaseStatusId { get; set; } public long? ChangedByUserId { get; set; } public string? Remarks { get; set; } public DateTime ChangedAt { get; set; } }

public sealed class JointDeclarationDetail { public long CaseId { get; set; } public string? DeclarationType { get; set; } public string? GroupName { get; set; } public string? TaskName { get; set; } public string? EnclosureNotes { get; set; } public DateTime? DeoReceivedAt { get; set; } public DateTime? DeoProcessedAt { get; set; } public string? DeoDecision { get; set; } public DateTime? SsReceivedAt { get; set; } public DateTime? SsProcessedAt { get; set; } public string? SsDecision { get; set; } public string? RejectionReason { get; set; } public long? AcknowledgedByUserId { get; set; } public long? ProcessedByUserId { get; set; } public GrievanceCase Case { get; set; } = null!; }
